version: '3.8'

services:
  bsv-legacy-bridge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bsv-legacy-bridge
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=8080
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s